#!/bin/sh

# remove symlinks created by ./install
rm ${HOME}/.Xresources \
	${HOME}/.Xresources-themes \
	${HOME}/.Xresources.d \
	${HOME}/.bash.d \
	${HOME}/.bash_profile \
	${HOME}/.bashrc \
	${HOME}/.bash_logout \
	${HOME}/.gitconfig \
	${HOME}/.gitconfig.user \
	${HOME}/.npmrc \
	${HOME}/.psqlrc \
	${HOME}/.screenrc \
	${HOME}/.tmux.conf \
	${HOME}/.vim \
	${HOME}/.vimrc
