#!/bin/bash

# Reload bash
alias reload='clear && . ~/.bashrc'

# For sudo-ing aliases
alias sudo='sudo '

# Run the last command as root
alias please='sudo $(fc -ln -1)'

# Linux info
alias whichlinux='uname -a; cat /etc/*release'

# Ip address
alias myip='dig +short myip.opendns.com @resolver1.opendns.com'

# Recursive phplint
alias phplint='find . -name "*.php" -exec php -l {} \; | grep "Parse error"'

# Cd
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# Ls
alias ls='ls --color=auto'
alias l='ls -lhF'
alias la='ls -lhAF'
alias lsd='ls -lhF | grep --color=never "^d"'

# Git
alias g='git'
alias gm='git merge --no-ff'
alias grb='git rebase -p'
alias gup='git fetch origin && grb origin/$(git_current_branch)'
alias gpthis='git push origin HEAD:$(git_current_branch)'

# Misc
alias h='history'
alias v='vim'
alias vimrc='vim ~/.vim/vimrc'
alias vg='vagrant'
alias vbm='VBoxManage'

# vim: ft=sh
