#!/bin/bash

if [ -f /etc/profile.d/bash-completion.sh ]; then
	. /etc/profile.d/bash-completion.sh
fi

case ${TERM} in
	xterm*) export TERM=xterm-256color;;
	screen*) export TERM=screen-256color;;
esac

[ -z "$PS1" ] && return

for file in 'aliases' 'colors' 'func' 'ssh' 'prompt' 'env'; do
	if [ -r ~/dotfiles/bash/${file} ]; then
		if [ ${file} == 'prompt' ]; then
			case "$TERM" in
				xterm*) . ~/dotfiles/bash/prompt ;;
				screen*) . ~/dotfiles/bash/prompt ;;
			esac
		else
			. ~/dotfiles/bash/${file}
		fi
	fi
done

# vim: ft=sh
